{
 "title": "Example - Simple",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Foo - total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    { "expr": "foo_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "{service_name=\"simple-example\"} |= ``"
    }
   ]
  },
  {
   "title": "My Num",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 8 },
   "targets": [
    { "expr": "my_num", "legendFormat": "__auto" }
   ]
  }
 ]
}